CPMCore/Controllers/ProjectenController.cs
using Microsoft.AspNetCore.Mvc;
using BOCore;
using DALCore;
using FacadeCore;
using ServiceCore;
using CPMCore.Models;
using CPMCore.Models.Projecten;
using CPMCore.Models.Klanten;
using CPMCore.Service;
using Microsoft.AspNetCore.Identity;
using System.Web;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Collections.Specialized;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using System.Collections;
using Microsoft.CodeAnalysis;
using CPMCore.Attributes;
using Rotativa.AspNetCore.Options;
using Microsoft.AspNetCore.Authorization;

namespace CPMCore.Controllers
{
    //tes
    public class ProjectenController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration Configuration;

        public ProjectenController(UserManager<ApplicationUser> userManager, ILogger<HomeController> logger, IConfiguration configuration)
        {
            _userManager = userManager;
            _logger = logger;
            Configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Breadcrumb("Info")]
        public ActionResult Detail(int projectid, bool EditGeneralData = false)
        {
            ViewBag.sidebarcollapsed = "sidebar-left-collapsed";
            ShowProjectDetail model = new ShowProjectDetail();
            var Service = ServiceFactory.GetProjectService();
            var cservice = ServiceFactory.GetClientService();
            var response = Service.GetProjectByID(projectid);
            if ((response.Success))
                model.Project = response.Value;
            model.Project.Postalcode.Country.CountryId = 19;
            model.Project.Postalcode.Country.ISOCode = "BE";
            model.ProjectName = model.Project.Name;
            FillInAddSelectListsDetail(ref model);
            model.GeneralDataEditMode = EditGeneralData;
            model.SelectedPostalcode = (int)model.Project.Postalcode.PostcodeId;
            model.Docs = Service.GetProjectDocs(projectid).Values;
            model.Users = _userManager.Users.ToList();
            model.Users = model.Users.OrderBy(m => m.Displayname).ToList();
            if (model.Project.ExecutionDays == 0)
                model.ExecutionDays = Service.GetProjectExecutionDays(model.Project.Id);
            else
                model.ExecutionDays = (int)model.Project.ExecutionDays;
            if (model.Project.StartDateConstruction is not null)
                model.StartDate = (DateOnly)model.Project.StartDateConstruction;
            else
                model.StartDate = Service.GetProjectStartDateConstruction(model.Project.Id);
            model.WorkingDaysLeft = -9999;
            if (model.ExecutionDays != 0 && model.StartDate != DateOnly.MinValue)
            {
                model.FinalConstructionDate = Service.GetFinalConstructionDay(model.Project.Id, model.StartDate, model.ExecutionDays);
                if (model.FinalConstructionDate != DateOnly.MinValue)
                    model.WorkingDaysLeft = Service.GetWorkingDaysLeft(model.FinalConstructionDate, model.Project.Id);
            }
            var response2 = cservice.GetClientAccountsByProjectIdLast5(projectid);
            if ((response2.Success))
                model.RecentClients = response2.Values;
            var response3 = Service.GetLatestProjectNews(1, projectid);
            if ((response3.Success))
                model.LatestNews = response3.Values.FirstOrDefault();
            if (model.LatestNews is not null)
            {
                if (model.LatestNews.TextNL is not null & model.LatestNews.TextNL.Length > 250)
                    model.LatestNews.TextNL = model.LatestNews.TextNL.Substring(0, 250).ToString() + " ...";
            }
            var response4 = Service.GetLatestProjectPictures(1, projectid);
            if ((response4.Success))
                model.LatestPicture = response4.Values.FirstOrDefault();
            var response5 = Service.GetLatestProjectDocs(5, projectid);
            if ((response5.Success))
                model.LatestDocs = response5.Values;
            return View(model);
        }
        //KLANTEN
        [HttpGet]
        [Breadcrumb("Klanten")]
        public ActionResult DetailClients(int projectid)
        {
            ViewBag.sidebarcollapsed = "sidebar-left-collapsed";
            DetailClientsModel model = new DetailClientsModel();
            var service = ServiceFactory.GetClientService();
            var service2 = ServiceFactory.GetProjectService();
            var response = service.GetClientAccountsByProjectIdWithUnits(projectid);
            if ((response.Success))
                model.ClientAccounts = response.Values;

            if (model.ClientAccounts.SelectMany(m => m.Units.Where(i => i.Type.GroupId == 1)).Count() > 0)
                model.ClientAccounts = model.ClientAccounts.OrderBy(m => m.Units.Where(a => a.Type.GroupId == 1).Count() > 0 ? m.Units.Where(a => a.Type.GroupId == 1).FirstOrDefault().Name : "", new ServiceCore.Helpers.AlphanumComparator()).ToList();
            model.ProjectId = projectid;
            model.ProjectName = service2.GetProjectNameById(projectid);
            return View(model);
        }

        //UNITS
        [HttpGet]
        [Breadcrumb("Eenheden")]
        public ActionResult DetailUnits(int projectid)
        {
            ViewBag.sidebarcollapsed = "sidebar-left-collapsed";
            return View(FillDetailUnitModel(projectid));
        }
        [HttpGet]
        [Breadcrumb("Eenheid toevoegen")]
        public ActionResult AddUnit(int projectid)
        {
            var referrer = Request.Headers["Referer"].ToString();

            // Use the referrer URL as needed
            ViewData["Referrer"] = referrer;
            var model = new AddUnitModel();
            var service = ServiceFactory.GetUnitService();
            var service2 = ServiceFactory.GetProjectService();

            // Get Units for attached unit select
            var u2response = service.GetUnitsByProjectIdForSelectAttachedUnit(projectid);
            if (u2response.Success) model.AttachableUnits = u2response.Values;

            // Get GroupTypes
            var responsegroup = service.GetUnitGroupTypes();
            if (responsegroup.Success) model.GroupTypes = responsegroup.Values;

            // Get Subtypes
            var responsetypes = service.GetUnitTypesByGroupId(model.SelectedGroupType);
            if (responsetypes.Success) model.Types = responsetypes.Values;

            model.ProjectId = projectid;
            model.ProjectName = service2.GetProjectNameById(projectid);
            model.ProjectLandShare = (int)service2.GetProjectLandshareById(projectid);

            var constval = new UnitConstructionValueBO();
            constval.PaymentGroupId = 0;
            model.ConstructionValues.Add(constval);

            var responsepaymentgroups = service2.GetProjectPaymentGroupsForSelect(projectid);
            if (responsepaymentgroups.Success) model.PaymentGroups = responsepaymentgroups.Values;
            ViewBag.paymentgroups = model.PaymentGroups;

            return View(model);
        }
        [HttpPost]
        public ActionResult AddUnit(DetailUnitsModel Model)
        {
            if (Model.SelectedType == 0)
                return RedirectToAction("DetailUnits", Model);
            ViewBag.sidebarcollapsed = "sidebar-left-collapsed";
            Model.AddUnit.ProjectId = Model.ProjectId;
            Model.AddUnit.Type.Id = Model.SelectedType;

            if (Model.AddUnit.AttachedUnitsId == 0)
                Model.AddUnit.AttachedUnitsId = null;
            var service = ServiceFactory.GetUnitService();
            var service2 = ServiceFactory.GetProjectService();
            var response = service.InsertUpdateUnit(Model.AddUnit);
            if (response.Success == true)
            {
                foreach (var item in Model.ConstructionValues)
                {
                    item.UnitId = response.InsertedId;
                    var responseConst = service.InsertUpdateConstructionValue(item);
                }
                Model.AddUnit.Name = "";
                var response2 = service.GetGroupedUnitsByProjectId(Model.ProjectId);
                Model.UnitsGrouped = response2.Values;
                // Get GroupTypes
                var responsegroup = service.GetUnitGroupTypes();
                if ((responsegroup.Success))
                    Model.GroupTypes = responsegroup.Values;
                // Get Subtypes
                var responsetypes = service.GetUnitTypesByGroupId(Model.SelectedGroupType);
                if ((responsetypes.Success))
                    Model.Types = responsetypes.Values;

                Model.ProjectName = service2.GetProjectNameById(Model.ProjectId);

                AddMessage("success", "De eenheid is aan het project toegevoegd", "Geslaagd!");
                return RedirectToAction("DetailUnits", new { projectid = Model.ProjectId });
            }
            else
            {
                AddMessage("error", "De eenheid is NIET toegevoegd, gelieve opnieuw tot proberen of contact op te nemen met de administrator", "Fout!");
                return RedirectToAction("DetailUnits", new { projectid = Model.ProjectId });
            }
        }
        [HttpGet]
        [Breadcrumb("Eenheid bewerken")]
        public ActionResult EditUnit(int projectid, int unitid)
        {
            var referrer = Request.Headers["Referer"].ToString();

            // Use the referrer URL as needed
            TempData["Referrer"] = referrer;
            EditUnitModel model = new EditUnitModel();
            var service = ServiceFactory.GetUnitService();
            var service2 = ServiceFactory.GetProjectService();

            // Get Unit

CPMCore/Views/Projecten/Partials/Clients.cshtml
@using BOCore
@model CPMCore.Models.Klanten.DetailClientsModel


@section PageStyle
{
<link rel="stylesheet" href="~/lib/magnific-popup/magnific-popup.css" />
<link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap5.css" />
}

<div class="inner-toolbar clearfix">
	<ul>
		@if (User.IsInRole("Admin"))
		{
			<li>
				<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Toevoegen klant" href="@Url.Action("AddClientAccount", "Klanten", new {id = Model.ProjectId})" class="AddClientAccount"><i class="fa fa-user-plus"></i></a>
			</li> 
		}

		<li>
			<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Wijzigingsopdrachten" href="@Url.Action("ChangeOrder", "Projecten", new {projectid = Model.ProjectId})" Class="ChangeOrder"><i Class="fa fa-shopping-cart"></i></a>
		</li>
	</ul>
</div>
@Html.HiddenFor(m => m.ProjectId, new {id = "txtProjectId"})
<div class="card card-modern pt-5">
	<div class="card-body">
		<div class="datatables-header-footer-wrapper mt-2">
			<div class="datatable-header">
				
			</div>

			<table class="table table-ecommerce-simple table-striped mb-0" id="datatable-clients-list" style="min-width: 550px;" data-toggle="table" data-show-columns="true" data-toolbar="#toolbar" data-toolbar-align="right">

				<thead>
					<tr>
						<th>Naam</th>
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 1).Count()) > 0) 
						{
							<th>Wooneenheid</th>
						}
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 4).Count()) > 0)
						{
							<th class="hidden-xs">Commerciële ruimte</th>
						}
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 3).Count()) > 0)
						{
							<th class="hidden-xs">Parkeergelegenheid</th>
						}
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 2).Count()) > 0)
						{
							<th class="hidden-xs">Berging</th>
						}
						<th class="hidden-xs" data-visible="false" data-sortable="true">Verkoopdatum</th>
						<th class="hidden-xs" data-visible="false" data-sortable="true">Aktedatum</th>
						<th class="hidden-xs" data-visible="false" data-sortable="true">Opleverdatum</th>
						<th class="hidden-xs noVis" data-sortable="false">Acties</th>
					</tr>
				</thead>
				<tbody>
					@foreach(var item in Model.ClientAccounts)
					{
						<tr>
							<td>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Klantgegevens" href="@Url.Action("Detail", "Klanten", new {clientid = item.Client.Id, projectid = Model.ProjectId})">
									@if (item.Client.Name is not null)
									{
										@item.Client.Salutation.GetDisplayName() @Html.Raw(" ") @item.Client.DisplayName
									}
									else
									{
										@item.Client.DisplayName
									}
								</a>
							</td>
						
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 1).Count()) > 0)
						{
							<td>
							@foreach (var unit in item.Units.Where(a => a.Type.GroupId == 1))
							{


										@unit.Type.Name @Html.Raw(" ") @unit.Name.ToUpper()
										@if (unit.Id != item.Units.Where(m => m.Type.GroupId == 1).Last().Id)
										{
											@Html.Raw(" - ")
										}
									
                                
                            }
								</td>
						}
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 4).Count()) > 0)
						{
							<td>
							@foreach (var unit in item.Units.Where(a => a.Type.GroupId == 4))
							{


										@unit.Type.Name	@Html.Raw(" ") @unit.Name.ToUpper()
										@if (unit.Id != item.Units.Where(m => m.Type.GroupId == 4).Last().Id)
										{
											@Html.Raw(" - ")
										}
									
								
							}
									</td>
						}
						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 3).Count()) > 0)
						{
							<td>
							@foreach (var unit in item.Units.Where(a => a.Type.GroupId == 3))
							{


										@unit.Type.Name	@Html.Raw(" ") @unit.Name.ToUpper()
										@if (unit.Id != item.Units.Where(m => m.Type.GroupId == 3).Last().Id)
										{
											@Html.Raw(" - ")
										}
									
								
							}
								</td>
						}

						@if (Model.ClientAccounts.Sum(m => m.Units.Where(a => a.Type.GroupId == 2).Count()) > 0)
						{
							<td>
							@foreach (var unit in item.Units.Where(a => a.Type.GroupId == 2))
							{


										@unit.Type.Name	@Html.Raw(" ") @unit.Name.ToUpper()
										@if (unit.Id != item.Units.Where(m => m.Type.GroupId == 2).Last().Id)
										{
											@Html.Raw(" - ")
										}
									
								
							}
								</td>
						}
							<td class="hidden-xs">@Html.DisplayFor(m => item.Client.DateSalesAgreement)</td>
							<td class="hidden-xs">@if (item.Client.DateDeedOfSale is not null)
									{
										@Html.DisplayFor(m => item.Client.DateDeedOfSale)
									}</td>
							<td class="hidden-xs">
										@if (item.Client.DeliveryDate is not null)
										{
											@Html.DisplayFor(m => item.Client.DeliveryDate)
										}
							</td>
							<td>
								  <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Bewerken"  id="editAccount" href="@Url.Action("Edit", "Klanten", new {projectid = Model.ProjectId, clientid = item.Client.Id, activetab = 0})"><i class="fa fa-edit"></i></a>
                                                @if(User.IsInRole("Admin")) {
                                                <a href="#modaldeleteclient" data-toggle="tooltip" id="deleteClient" data-placement="top" title="" data-original-title="Verwijderen" class="deleteClient" data-id="@item.Client.Id"><i class="fa fa-remove "></i></a>
												}
							</td>
						</tr>

					}
				</tbody>
			</table>
@* 			<hr class="solid mt-5 opacity-4">
			<div class="datatable-footer">
				<div class="row align-items-center justify-content-between mt-3">
					<div class="col-md-auto order-1 mb-3 mb-lg-0">
						<div class="d-flex align-items-stretch">
							<div class="d-grid gap-3 d-md-flex justify-content-md-end me-4">
								<select class="form-control select-style-1 bulk-action" name="bulk-action" style="min-width: 170px;">
									<option value="" selected>Bulk Actions</option>
									<option value="delete">Delete</option>
								</select>
								<a href="#" class="bulk-action-apply btn btn-light btn-px-4 py-3 border font-weight-semibold text-color-dark text-3">Apply</a>
							</div>
						</div>
					</div>
					<div class="col-lg-auto text-center order-3 order-lg-2">
						<div class="results-info-wrapper"></div>
					</div>
					<div class="col-lg-auto order-2 order-lg-3 mb-3 mb-lg-0">
						<div class="pagination-wrapper"></div>
					</div>
				</div>
			</div> *@
		</div>
	</div>

</div>

CPMCore/Views/Projecten/Partials/Contracts.cshtml
@using BOCore
@model CPMCore.Models.Projecten.DetailContractsModel


@section PageStyle
{
<link rel="stylesheet" href="~/lib/magnific-popup/magnific-popup.css" />
<link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap5.css" />
}

@Html.HiddenFor(m => m.ProjectId, new {id = "txtProjectId"})
<div class="card card-modern">
	<div class="card-body">
		<div class="datatables-header-footer-wrapper mt-2">
			<div class="datatable-header">
				<div class="row align-items-center mb-3">

					<div class="col-12 col-lg-auto mb-3 mb-lg-0">
						<button type="button" class="btn btn-primary btn-md font-weight-semibold btn-py-2 px-4" id="btnExportExcel"><i class="fas fa-file-excel"></i></button>
						<button type="button" class="btn btn-primary btn-md font-weight-semibold btn-py-2 px-4" id="btnExportPdf"><i class="fas fa-file-pdf"></i></button>
						<a href="@Url.Action("AddContract", "Projecten", new {projectid = Model.ProjectId})" class="btn btn-primary btn-md font-weight-semibold btn-py-2 px-4">+ Contract toevoegen</a>
					</div>
					<div class="col-8 col-lg-auto ms-auto ml-auto mb-3 mb-lg-0">
					</div>
					<div class="col-4 col-lg-auto ps-lg-1 mb-3 mb-lg-0">
					</div>
					<div class="col-12 col-lg-auto ps-lg-1">
						<div class="search search-style-1 search-style-1-lg mx-lg-auto">
							<div class="input-group">
								<input type="text" class="search-term form-control" name="search-term" id="search-term" placeholder="Zoeken">
								<button class="btn btn-default" type="submit"><i class="bx bx-search"></i></button>
							</div>
						</div>
					</div>
				</div>
			</div>

			<table class="table table-ecommerce-simple table-striped mb-0" id="datatable-contracts-list" style="min-width: 550px;" data-toggle="table" data-show-columns="true" data-toolbar-align="right">

				<thead>
					<tr>
						<th data-sortable="false">Status</th>
						<th data-sortable="true">Bedrijf</th>
						<th data-sortable="true" class="text-right">Contractprijs</th>
						<th data-sortable="false" class="hidden-xs text-right">BTW %</th>
						<th data-sortable="false" class="hidden-xs text-right">Betaaltermijn</th>
						<th data-sortable="false" class="hidden-xs text-right">Korting contant</th>
						<th data-sortable="false" class="hidden-xs text-right">Borg</th>
						<th class="hidden-xs noVis" data-sortable="false">Acties</th>
					</tr>
				</thead>
				<tbody>
					@foreach(var item in Model.Contracts.OrderBy(m => m.Company.Display))
					{
						<tr>
							<td>
								@if (item.ContractSigned == true)
								{
									<span class="ecommerce-status completed"></span>
								}
								else
								{
									<span class="ecommerce-status failed"></span>
								}
							</td>
							<td>
								@item.Company.Display
							</td>
							<td>
								@String.Format("{0:C}", item.Activities.Sum(m => m.Price))
							</td>
							<td>
								@if (item.VatPercentage != null)
								{
									@Html.DisplayFor(m => item.VatPercentage)
								}
								else
								{
                                    @Html.Raw("-")
                                }
							</td>
							<td>
								@if (item.PaymentTerm != null)
								{
									@Html.DisplayFor(m => item.PaymentTerm) @Html.Raw(" dagen")
								}
								else
								{
									@Html.Raw("-")
								}
							</td>
							<td>
								@if (item.CashDiscount != false)
								{
									@Html.DisplayFor(m => item.CashDiscountPercentage) @Html.Raw(" binnen de ") @Html.DisplayFor(m => item.CashDiscountPaymentTerm) @Html.Raw(" dagen")
								}
								else
								{
									@Html.Raw("-")
								}
							</td>
							<td>
								@if (item.GuaranteeType == ContractGuaranteeType.FinancialGuarantee)
								{
									@Html.DisplayFor(m => item.GuaranteePercentage) @Html.Raw(" ") @item.GuaranteeType.GetDisplayName()
								}
								else
								{
									@item.GuaranteeType.GetDisplayName()
								}
							</td>					
							<td>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Bewerken"  id="editContract" href="@Url.Action("EditContract", "Projecten", new {projectid = Model.ProjectId, contractid = item.Id})"><i class="fa fa-edit"></i></a>
								<a href="#modaldeletecontract" data-toggle="tooltip" id="deleteContract" data-placement="top" title="" data-original-title="Verwijderen" class="deleteContract" data-id="@item.Id"><i class="fa fa-remove "></i></a>
												
							</td>
						</tr>

					}
				</tbody>
			</table>
		</div>
	</div>

</div>

CPMCore/Views/Projecten/Partials/_ActivityRow.cshtml
@using BOCore
@using HtmlHelpers.BeginCollectionItemCore
@using System.Globalization
@model ContractActivityBO

<div class="row align-items-center pb-3">
    @using (Html.BeginCollectionItem("activities")) {

        @Html.HiddenFor(m => m.ContractActivityId)
        @Html.HiddenFor(m => m.ContractId)
        @Html.HiddenFor(m => m.Activity.ID)
        @Html.HiddenFor(m => m.Activity.Name)
        <label class="col-lg-4 col-xl-3 control-label text-lg-end mb-0">@Model.Activity.Name</label>
        <div class="col-lg-8 col-xl-6">
            <div class="input-group mb-3">
                <span class="input-group-text">€</span>
                @Html.TextBoxFor(m => m.Price, new
                    {
                        @class = "form-control form-control-modern Currencymask",
                        @Value = Model.Price.HasValue ? Model.Price.Value.ToString("0.##", CultureInfo.InvariantCulture) : ""
                    })
                @if (ViewData["mode"] == "edit")
                {
                    <button class="btn btn-danger deleteUnit" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" ms-2" data-id="@Model.Activity.ID"><i class="fa fa-remove"></i></button>

                }
                else if (ViewData["mode"] == "add")
                {
                    <button class="btn btn-danger deleterow" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" data-id="@Model.Activity.ID"><i class="fa fa-remove"></i></button>

                }
            </div>
            
        </div>

       
}
</div>


          

CPMCore/Views/Projecten/Partials/_AdditionalOrderRow.cshtml
@using BOCore
@using HtmlHelpers.BeginCollectionItemCore
@model ContractActivityBO 

    @using (Html.BeginCollectionItem("activities")) {
        @Html.HiddenFor(m => m.ContractActivityId)
        @Html.HiddenFor(m => m.ContractId)
        @Html.HiddenFor(m => m.Activity.ID)
        @Html.HiddenFor(m => m.Activity.Name)
    <div class="row align-items-center pb-3">
        <label class="col-lg-4 col-xl-3 control-label text-lg-end mb-0">@Model.Activity.Name</label>
        <div class="col-lg-8 col-xl-6">
            <div class="input-group mb-3">
                <span class="input-group-text">€</span>
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control form-control-modern Currencymask" })
                @if (ViewData["mode"] == "edit")
                {
                    <button class="btn btn-danger deleteUnit" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" ms-2" data-id="@Model.Activity.ID"><i class="fa fa-remove"></i></button>

                }
                else if (ViewData["mode"] == "add")
                {
                    <button class="btn btn-danger deleterow" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" data-id="@Model.Activity.ID"><i class="fa fa-remove"></i></button>

                }
            </div>
            
        </div>
    </div>
       
}



          

CPMCore/Views/Projecten/Partials/_ConstructionValueRow.cshtml
@using BOCore
@using HtmlHelpers.BeginCollectionItemCore
@model UnitConstructionValueBO 
<tr>
    @using (Html.BeginCollectionItem("ConstructionValues")) {
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.UnitId)
        <td width="30%">
            @Html.EditorFor(m => m.Value, new {@class = "form-control form-control-modern", id = "txtValue", placeholder="Bouwwaarde"})
        </td>
        <td width="30%">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control form-control-modern", id = "txtDescription", placeholder = "Omschrijving" })
    </td>
        <td width="35%">
            @Html.DropDownListFor(m => m.PaymentGroupId, new SelectList(ViewBag.Paymentgroups, "ID", "Display", Model.PaymentGroupId, "Group"), "Selecteer betalingsgroep ...", new { @class = "form-control form-control-modern populate", id = "lstpaymentgroups, " })
    </td>
    <td width="5%">
        <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" Class="deleteConstructionRow ms-2"><i Class="fa fa-remove"></i></a>
    </td>

    }
</tr>

CPMCore/Views/Projecten/Partials/_RoomEditorRow.cshtml
@using BOCore
@using HtmlHelpers.BeginCollectionItemCore
@model RoomBO


@using(Html.BeginCollectionItem("rooms")){
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.UnitId)
        <div class="form-group row justify-content-center ecommerce-attribute-row mb-2">
        <div class="col-lg-5 col-xl-3"> @Html.DropDownListFor(m => m.Type, Html.GetEnumSelectList(Model.Type.GetType()), new { @class = "form-control form-control-modern", id = "lstType" })</div>
            <div class="col-lg-1 col-xl-1">
                @Html.TextBoxFor(m => m.Number, new { type = "number", @class = "form-control form-control-modern", id = "txtNumber" })
            </div>
            <div class="col-lg-1 col-xl-1">
                @Html.EditorFor(m => m.Surface, new { @class = "form-control form-control-modern", id = "txtSurface" })
            </div>
            <div class="col-lg-3 col-xl-4">
                @Html.TextBoxFor(m => m.Remark, new { @class = "form-control form-control-modern", id = "txtRemark" })
            </div>
            <div class="col-lg-1 col-xl-1">
                <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Verwijderen" Class="deleteRow"><i Class="fa fa-remove"></i></a>
            </div>
        </div>
}